# Generated by Django 4.1.7 on 2023-03-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_message_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', 'created']},
        ),
    ]
